// Auth
export const EMAIL_LOGIN_REQUEST = 'SS/EMAIL_LOGIN_REQUEST';
export const EMAIL_LOGIN_SUCCESS = 'SS/EMAIL_LOGIN_SUCCESS';
export const EMAIL_LOGIN_FAILURE = 'SS/EMAIL_LOGIN_FAILURE';

// User
export const USER_DETAILS_REQUEST = 'SS/USER_DETAILS_REQUEST';
export const USER_DETAILS_SUCCESS = 'SS/USER_DETAILS_SUCCESS';
export const USER_DETAILS_FAILURE = 'SS/USER_DETAILS_FAILURE';

export const USER_DETAILS_UPDATE_REQUEST = 'SS/USER_DETAILS_UPDATE_REQUEST';
export const USER_DETAILS_UPDATE_SUCCESS = 'SS/USER_DETAILS_UPDATE_SUCCESS';
export const USER_DETAILS_UPDATE_FAILURE = 'SS/USER_DETAILS_UPDATE_FAILURE';
